In [1]:
import pickle
from typing import Dict, List, Tuple
from itertools import product
import pandas as pd
import time
import numpy as np

___

In [2]:
data = np.asarray(range(1536))

In [24]:
data = np.asarray(48*[16*[list(range(1536))]]).T

In [42]:
data.shape

(1536, 16, 48)

In [43]:
data

array([[[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0]],

       [[   1,    1,    1, ...,    1,    1,    1],
        [   1,    1,    1, ...,    1,    1,    1],
        [   1,    1,    1, ...,    1,    1,    1],
        ...,
        [   1,    1,    1, ...,    1,    1,    1],
        [   1,    1,    1, ...,    1,    1,    1],
        [   1,    1,    1, ...,    1,    1,    1]],

       [[   2,    2,    2, ...,    2,    2,    2],
        [   2,    2,    2, ...,    2,    2,    2],
        [   2,    2,    2, ...,    2,    2,    2],
        ...,
        [   2,    2,    2, ...,    2,    2,    2],
        [   2,    2,    2, ...,    2,    2,    2],
        [   2,    2,    2, ...,    2,    2,    2]],

       ...,

       [[1533, 1533, 153

In [34]:
h = data.shape[0]
n_seconds_split = 3
x_split = h//n_seconds_split
print(h, x_split)
print(list(range(x_split, h, x_split)))

1536 512
[512, 1024]


In [36]:
splitted_data = np.split(data, range(x_split, h, x_split))

In [68]:
splitted_data[1].shape

(512, 16, 48)

In [46]:
splitted_data[0].shape

(512, 16, 48)

In [48]:
print(splitted_data[0][:, :, 0])
print(splitted_data[1][:, :, 0])
print(splitted_data[2][:, :, 0])

[[  0   0   0 ...   0   0   0]
 [  1   1   1 ...   1   1   1]
 [  2   2   2 ...   2   2   2]
 ...
 [509 509 509 ... 509 509 509]
 [510 510 510 ... 510 510 510]
 [511 511 511 ... 511 511 511]]
[[ 512  512  512 ...  512  512  512]
 [ 513  513  513 ...  513  513  513]
 [ 514  514  514 ...  514  514  514]
 ...
 [1021 1021 1021 ... 1021 1021 1021]
 [1022 1022 1022 ... 1022 1022 1022]
 [1023 1023 1023 ... 1023 1023 1023]]
[[1024 1024 1024 ... 1024 1024 1024]
 [1025 1025 1025 ... 1025 1025 1025]
 [1026 1026 1026 ... 1026 1026 1026]
 ...
 [1533 1533 1533 ... 1533 1533 1533]
 [1534 1534 1534 ... 1534 1534 1534]
 [1535 1535 1535 ... 1535 1535 1535]]


In [52]:
stacked_data = np.dstack(splitted_data)

In [53]:
stacked_data.shape

(512, 16, 144)

In [61]:
stacked_data[:, :, 0]

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ...,
       [509, 509, 509, ..., 509, 509, 509],
       [510, 510, 510, ..., 510, 510, 510],
       [511, 511, 511, ..., 511, 511, 511]])

In [60]:
stacked_data[:, :, 48]

array([[ 512,  512,  512, ...,  512,  512,  512],
       [ 513,  513,  513, ...,  513,  513,  513],
       [ 514,  514,  514, ...,  514,  514,  514],
       ...,
       [1021, 1021, 1021, ..., 1021, 1021, 1021],
       [1022, 1022, 1022, ..., 1022, 1022, 1022],
       [1023, 1023, 1023, ..., 1023, 1023, 1023]])

In [62]:
stacked_data[:, :, 2*48]

array([[1024, 1024, 1024, ..., 1024, 1024, 1024],
       [1025, 1025, 1025, ..., 1025, 1025, 1025],
       [1026, 1026, 1026, ..., 1026, 1026, 1026],
       ...,
       [1533, 1533, 1533, ..., 1533, 1533, 1533],
       [1534, 1534, 1534, ..., 1534, 1534, 1534],
       [1535, 1535, 1535, ..., 1535, 1535, 1535]])

In [63]:
transposed_stacked_data = stacked_data.transpose(2, 0, 1)

In [64]:
transposed_stacked_data.shape

(144, 512, 16)

In [65]:
transposed_stacked_data[0, :, :]

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ...,
       [509, 509, 509, ..., 509, 509, 509],
       [510, 510, 510, ..., 510, 510, 510],
       [511, 511, 511, ..., 511, 511, 511]])

In [66]:
transposed_stacked_data[48, :, :]

array([[ 512,  512,  512, ...,  512,  512,  512],
       [ 513,  513,  513, ...,  513,  513,  513],
       [ 514,  514,  514, ...,  514,  514,  514],
       ...,
       [1021, 1021, 1021, ..., 1021, 1021, 1021],
       [1022, 1022, 1022, ..., 1022, 1022, 1022],
       [1023, 1023, 1023, ..., 1023, 1023, 1023]])

In [67]:
transposed_stacked_data[2*48, :, :]

array([[1024, 1024, 1024, ..., 1024, 1024, 1024],
       [1025, 1025, 1025, ..., 1025, 1025, 1025],
       [1026, 1026, 1026, ..., 1026, 1026, 1026],
       ...,
       [1533, 1533, 1533, ..., 1533, 1533, 1533],
       [1534, 1534, 1534, ..., 1534, 1534, 1534],
       [1535, 1535, 1535, ..., 1535, 1535, 1535]])

__Extracting statistics from a saved object__

In [2]:
def load_stats_file(path: str) -> Dict:
    with open(path, 'rb') as stats_file: stats = pickle.load(stats_file)
    return stats

def singlefold_best_stats(path: str, specifications: str, *args) -> List[float]:
    return _singlefold_best_stats(load_stats_file(path + specifications.format(*args)))

def _singlefold_best_stats(statistics: Dict) -> List[float]:
    return statistics['BestLoss']

def kfold_best_stats(path: str, specifications: str, *args) -> pd.DataFrame:
    return _kfold_best_stats(load_stats_file(path + specifications.format(*args)))
    
def _kfold_best_stats(statistics: Dict) -> List[float]:
    accuracy = []
    loss = []
    
    for fold in range(len(statistics) - 1):
        accuracy.append(statistics['Fold {}'.format(fold)]['BestAccuracy'])
        loss.append(statistics['Fold {}'.format(fold)]['BestLoss'])
    
    accuracy.append(np.mean(accuracy))
    loss.append(np.mean(loss))
    accuracy.append(np.std(accuracy[:-1]))
    loss.append(np.std(loss[:-1]))
    
    return accuracy, loss

In [186]:
path = 'Outputs/Model (1 Layer)/ResNet50 - N-TL - Autoencoder - '
S = [1]
K = [1, 3, 5]
FM = [1, 3, 5]
cols = ['F1', 'F2', 'F3', 'F4', 'F5', 'M', 'STD']
table = pd.DataFrame(columns = cols, index = map(lambda x: str(x), list(product(S, K, FM))))
for (s, k, fm) in product(S, K, FM):
    best_stats = kfold_best_stats(path, 's = {} k = {} fm = {} - 5 classes - stats', s, k, fm)
    for i in range(len(cols)):
        table.loc[str((s, k, fm))][cols[i]] = best_stats[0][i]

table

F1        F2        F3        F4        F5         M  \
(1, 1, 1)  0.833333  0.841503  0.820261  0.795752  0.795752   0.81732   
(1, 1, 3)   0.52451  0.629085  0.702614  0.555556  0.619281  0.606209   
(1, 1, 5)  0.503268  0.444444  0.818627  0.676471  0.627451  0.614052   
(1, 3, 1)  0.761438   0.79902  0.800654  0.702614   0.79902  0.772549   
(1, 3, 3)  0.405229  0.403595  0.535948  0.433007  0.411765  0.437908   
(1, 3, 5)  0.550654  0.415033  0.503268  0.553922   0.48366  0.501307   
(1, 5, 1)  0.723856  0.805556   0.79902  0.705882  0.754902  0.757843   
(1, 5, 3)  0.614379  0.704248  0.638889  0.568627  0.694444  0.644118   
(1, 5, 5)  0.705882  0.444444   0.51634  0.612745  0.547386  0.565359   

                STD  
(1, 1, 1)   0.01887  
(1, 1, 3)  0.062014  
(1, 1, 5)  0.131884  
(1, 3, 1)  0.037962  
(1, 3, 3)  0.050129  
(1, 3, 5)  0.050915  
(1, 5, 1)  0.039587  
(1, 5, 3)  0.050515  
(1, 5, 5)    0.0887

In [8]:
path = 'Outputs/Model (1 Layer)/50 folds - ResNet50 - N-TL - 50 folds - Autoencoder - '
S = [2]
K = [1, 3, 5]
FM = [1, 3, 5]
DP = [0]
cols = ['F1', 'F2', 'F3', 'F4', 'F5', 'M', 'STD']
table = pd.DataFrame(columns = cols, index = map(lambda x: str(x), list(product(S, K, FM, DP))))
for (s, k, fm, dp) in product(S, K, FM, DP):
    best_stats = kfold_best_stats(path, 's = {} k = {} fm = {} dp = {} - 5 classes - stats', s, k, fm, dp)
    for i in range(len(cols)):
        table.loc[str((s, k, fm, dp))][cols[i]] = best_stats[0][i]

table

F1        F2        F3        F4        F5         M  \
(2, 1, 1, 0)  0.735294  0.697712  0.746732  0.764706  0.727124  0.734314   
(2, 1, 3, 0)  0.496732  0.462418  0.398693  0.591503  0.413399  0.472549   
(2, 1, 5, 0)  0.598039  0.630719  0.645425  0.428105  0.539216  0.568301   
(2, 3, 1, 0)   0.79902   0.80719   0.80719  0.771242  0.816993  0.800327   
(2, 3, 3, 0)  0.637255  0.377451  0.679739       0.5  0.598039  0.558497   
(2, 3, 5, 0)   0.77451  0.480392  0.514706  0.408497  0.609477  0.557516   
(2, 5, 1, 0)  0.821895  0.800654  0.650327  0.792484  0.825163  0.778105   
(2, 5, 3, 0)  0.377451  0.403595  0.472222  0.593137  0.395425  0.448366   
(2, 5, 5, 0)  0.444444  0.519608  0.359477  0.400327  0.408497  0.426471   

                   STD  
(2, 1, 1, 0)  0.022227  
(2, 1, 3, 0)   0.06898  
(2, 1, 5, 0)  0.079031  
(2, 3, 1, 0)  0.015618  
(2, 3, 3, 0)  0.108319  
(2, 3, 5, 0)  0.126312  
(2, 5, 1, 0)  0.065076  
(2, 5, 3, 0)  0.079201  
(2, 5, 5, 0)  0.053837

In [189]:
path = 'Outputs/Model (1 Layer + Dropout)/ResNet50 - N-TL - Autoencoder - '
S = [1]
K = [1]
FM = [1]
DP = [0.1, 0.15, 0.2, 0.25, 0.5, 0.75]
cols = ['F1', 'F2', 'F3', 'F4', 'F5', 'M', 'STD']
table = pd.DataFrame(columns = cols, index = map(lambda x: str(x), list(product(S, K, FM, DP))))
for (s, k, fm, dp) in product(S, K, FM, DP):
    best_stats = kfold_best_stats(path, 's = {} k = {} fm = {} dp = {} - 5 classes - stats', s, k, fm, dp)
    for i in range(len(cols)):
        table.loc[str((s, k, fm, dp))][cols[i]] = best_stats[0][i]

table

F1        F2        F3        F4        F5         M  \
(1, 1, 1, 0.1)   0.794118  0.856209  0.736928  0.851307  0.851307  0.817974   
(1, 1, 1, 0.15)  0.810458  0.800654  0.866013  0.854575  0.843137  0.834967   
(1, 1, 1, 0.2)   0.838235  0.633987  0.834967   0.54085  0.795752  0.728758   
(1, 1, 1, 0.25)  0.555556  0.831699  0.859477  0.810458  0.728758   0.75719   
(1, 1, 1, 0.5)   0.361111  0.397059  0.297386  0.253268  0.437908  0.349346   
(1, 1, 1, 0.75)   0.28268  0.267974  0.222222  0.223856  0.235294  0.246405   

                      STD  
(1, 1, 1, 0.1)   0.046522  
(1, 1, 1, 0.15)  0.025271  
(1, 1, 1, 0.2)   0.120037  
(1, 1, 1, 0.25)  0.109833  
(1, 1, 1, 0.5)   0.066617  
(1, 1, 1, 0.75)  0.024486

In [11]:
path = 'Outputs/Model (1 Layer)/50 folds - Autoencoder - '
S = [2]
K = [1, 3, 5]
FM = [1, 3, 5]
DP = [0]
cols = ['Loss']
table = pd.DataFrame(columns = cols, index = map(lambda x: str(x), list(product(S, K, FM, DP))))
for (s, k, fm, dp) in product(S, K, FM, DP):
    best_stats = singlefold_best_stats(path, 's = {} k = {} fm = {} dp = {} - 5 classes - stats', s, k, fm, dp)
    table.loc[str((s, k, fm, dp))]['Loss'] = best_stats
    
table

Loss
(2, 1, 1, 0)  0.438167
(2, 1, 3, 0)   0.26566
(2, 1, 5, 0)  0.193839
(2, 3, 1, 0)  0.254984
(2, 3, 3, 0)  0.180626
(2, 3, 5, 0)  0.148386
(2, 5, 1, 0)  0.249937
(2, 5, 3, 0)  0.158963
(2, 5, 5, 0)  0.117496

In [194]:
path = 'Outputs/Model (1 Layer + Dropout)/Autoencoder - '
S = [1]
K = [1]
FM = [1]
DP = [0.1, 0.15, 0.2, 0.25, 0.5, 0.75]
cols = ['Loss']
table = pd.DataFrame(columns = cols, index = map(lambda x: str(x), list(product(S, K, FM, DP))))
for (s, k, fm, dp) in product(S, K, FM, DP):
    best_stats = singlefold_best_stats(path, 's = {} k = {} fm = {} dp = {} - 5 classes - stats', s, k, fm, dp)
    table.loc[str((s, k, fm, dp))]['Loss'] = best_stats
    
table

Loss
(1, 1, 1, 0.1)   0.199067
(1, 1, 1, 0.15)   0.21271
(1, 1, 1, 0.2)   0.236202
(1, 1, 1, 0.25)  0.242042
(1, 1, 1, 0.5)   0.562208
(1, 1, 1, 0.75)  0.827955

__Extracting statistics from log files__

In [4]:
def _read_folds_from_file(path: str, epochs: int) -> Dict:
    file = open(path).readlines()
    return [file[i+3:i+3+2*epochs+3] for i in range(0, len(file) - 1, 2*epochs + 7)]

def extract_values(path: str, epochs: int) -> Tuple[Dict]:
    folds = _read_folds_from_file(path, epochs)[:-1]
    training = {}
    validation = {}
    for i, f in enumerate(folds):
        training[i + 1] = [np.asarray([]), np.asarray([])]  # loss = 0, accuracy = 1
        validation[i + 1] = [np.asarray([]), np.asarray([])]
        for line in f:
            if 'Training' in line and 'complete' not in line:
                training[i+1][0] = np.append(training[i+1][0], float(line[21:25]))
                training[i+1][1] = np.append(training[i+1][1], float(line[29:34]))
            if 'Validation' in line and 'Best' not in line:
                validation[i+1][0] = np.append(validation[i+1][0], float(line[21:25]))
                validation[i+1][1] = np.append(validation[i+1][1], float(line[29:34]))

            if 'Best Validation Accuracy' in line:
                validation[i + 1].append(float(line[26:30]))

            if 'Best Validation Loss' in line:
                validation[i+1].append(float(line[22:26]))
                
    return training, validation

def get_best_validation(validation_data: Dict):
    best_acc = []
    best_loss = []
    
    for fold in validation_data.keys():
        best_acc.append(validation_data[fold][-2])
        best_loss.append(validation_data[fold][-1])
    
    best_acc.append(np.mean(best_acc)); best_acc.append(np.std(best_acc[:-1]))
    best_loss.append(np.mean(best_loss)); best_loss.append(np.std(best_loss[:-1]))
    
    return best_acc, best_loss

In [129]:
path = 'Outputs/Training - Resnet18 - Pretrained - 5 Classes - Adam - Feb-18-2021.log'
epochs = 50
training, validation = extract_values(path, epochs)
best_validation_acc, best_validation_loss = get_best_validation(validation)
print(best_validation_acc)

[0.85, 0.81, 0.86, 0.84, 0.82, 0.836, 0.01854723699099139]


In [130]:
path = 'Outputs/Training - Resnet18 - N Pretrained - 5 Classes - Adam - Feb-18-2021.log'
epochs = 50
training, validation = extract_values(path, epochs)
best_validation_acc, best_validation_loss = get_best_validation(validation)
print(best_validation_acc)

[0.82, 0.81, 0.82, 0.78, 0.82, 0.8099999999999999, 0.015491933384829638]


***

In [32]:
cols = ['Length', 'F1', 'F2', 'F3', 'F4', 'F5', 'Mean', 'Std']
table = pd.DataFrame(columns = cols).set_index('Length')

In [45]:
path = 'Outputs/Training - Resnet18 - N Pretrained - 5 Classes - Adam - 250 - 26 Subjects - Feb-22-2021.log'
epochs = 50
training, validation = extract_values(path, epochs)
best_validation_acc, best_validation_loss = get_best_validation(validation)
print(best_validation_acc)

[0.8, 0.78, 0.78, 0.78, 0.79, 0.7860000000000001, 0.008000000000000007]


In [46]:
table.loc['250 - 26'] = best_validation_acc

In [47]:
table

F1    F2    F3    F4    F5   Mean       Std
Length                                                  
1000 - 35  0.80  0.90  0.89  0.89  0.82  0.860  0.041473
750 - 35   0.84  0.84  0.86  0.84  0.83  0.842  0.009798
500 - 26   0.84  0.83  0.83  0.85  0.83  0.836  0.008000
250 - 35   0.78  0.77  0.77  0.78  0.78  0.776  0.004899
250 - 26   0.80  0.78  0.78  0.78  0.79  0.786  0.008000

***

In [74]:
cols = ['Length', 'F1', 'F2', 'F3', 'F4', 'F5', 'Mean', 'Std']
table = pd.DataFrame(columns = cols).set_index('Length')

In [66]:
path = 'Outputs/Training - Resnet18 - Pretrained - 5 Classes - Adam - 1500 - Feb-21-2021.log'
epochs = 50
training, validation = extract_values(path, epochs)
best_validation_acc, best_validation_loss = get_best_validation(validation)
print(best_validation_acc)

[0.42, 0.48, 0.5, 0.5, 0.5, 0.48, 0.030983866769659345]


In [67]:
table.loc['1500 - 35'] = best_validation_acc

In [89]:
table

F1    F2    F3    F4    F5   Mean       Std
Length                                                  
1000 - 26  0.93  0.87  0.77  0.90  0.79  0.852  0.062097
750 - 35   0.48  0.54  0.45  0.52  0.47  0.492  0.033106
500 - 26   0.74  0.82  0.56  0.85  0.88  0.770  0.114891
500 - 1    0.84  0.85  0.85  0.88  0.87  0.858  0.014697
250 - 35   0.39  0.33  0.44  0.50  0.39  0.410  0.056921
250 - 26   0.80  0.80  0.79  0.79  0.78  0.792  0.007483
1500 - 35  0.79  0.80  0.82  0.80  0.80  0.802  0.009798