In [1]:
from __future__ import print_function # What is that?
import torch

In [5]:
X = torch.empty(5, 3)
print(X)

tensor([[9.6429e-39, 9.8265e-39, 5.9694e-39],
        [8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39]])


In [6]:
X = torch.rand(5, 3)
print(X)

tensor([[0.8069, 0.1464, 0.7867],
        [0.3557, 0.9087, 0.1259],
        [0.2892, 0.1047, 0.6829],
        [0.5045, 0.2029, 0.5566],
        [0.1056, 0.6157, 0.2313]])


In [16]:
X = torch.zeros(5, 3, dtype = torch.long)
print(X)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [19]:
X = torch.tensor([5.5, 3])
print(X)

tensor([5.5000, 3.0000])


In [23]:
X = torch.tensor([[5.5], [3]])
print(X)

tensor([[5.5000],
        [3.0000]])


In [28]:
X = X.new_ones(5, 3, dtype = torch.double)
print(X)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [56]:
X = torch.randn_like(X, dtype = torch.float)
print(X)

tensor([[-0.5985,  0.3188,  0.6822,  0.9907],
        [ 2.5392,  0.8281,  0.1896,  1.0113],
        [-0.6257,  0.6534, -1.5487, -1.2649],
        [-0.9367, -0.8208, -0.0733, -0.2934],
        [-1.1888, -0.4929, -1.3146, -1.2630]])


In [59]:
Y = torch.rand(5, 4)
print(Y)

tensor([[0.5981, 0.4840, 0.0751, 0.3412],
        [0.1793, 0.1599, 0.8514, 0.1643],
        [0.4888, 0.3092, 0.1587, 0.2879],
        [0.6893, 0.5056, 0.4527, 0.7101],
        [0.8926, 0.4788, 0.5785, 0.5306]])


In [60]:
print(X+Y)

tensor([[-4.0871e-04,  8.0281e-01,  7.5737e-01,  1.3318e+00],
        [ 2.7185e+00,  9.8795e-01,  1.0410e+00,  1.1756e+00],
        [-1.3696e-01,  9.6261e-01, -1.3900e+00, -9.7699e-01],
        [-2.4740e-01, -3.1528e-01,  3.7935e-01,  4.1663e-01],
        [-2.9621e-01, -1.4094e-02, -7.3601e-01, -7.3237e-01]])


In [64]:
print(torch.add(X, Y))

tensor([[-4.0871e-04,  8.0281e-01,  7.5737e-01,  1.3318e+00],
        [ 2.7185e+00,  9.8795e-01,  1.0410e+00,  1.1756e+00],
        [-1.3696e-01,  9.6261e-01, -1.3900e+00, -9.7699e-01],
        [-2.4740e-01, -3.1528e-01,  3.7935e-01,  4.1663e-01],
        [-2.9621e-01, -1.4094e-02, -7.3601e-01, -7.3237e-01]])


In [66]:
result = torch.empty(5, 3)
torch.add(X, Y, out = result)
result

tensor([[-4.0871e-04,  8.0281e-01,  7.5737e-01,  1.3318e+00],
        [ 2.7185e+00,  9.8795e-01,  1.0410e+00,  1.1756e+00],
        [-1.3696e-01,  9.6261e-01, -1.3900e+00, -9.7699e-01],
        [-2.4740e-01, -3.1528e-01,  3.7935e-01,  4.1663e-01],
        [-2.9621e-01, -1.4094e-02, -7.3601e-01, -7.3237e-01]])

In [67]:
Y.add_(X) # in place
print(Y)

tensor([[-4.0871e-04,  8.0281e-01,  7.5737e-01,  1.3318e+00],
        [ 2.7185e+00,  9.8795e-01,  1.0410e+00,  1.1756e+00],
        [-1.3696e-01,  9.6261e-01, -1.3900e+00, -9.7699e-01],
        [-2.4740e-01, -3.1528e-01,  3.7935e-01,  4.1663e-01],
        [-2.9621e-01, -1.4094e-02, -7.3601e-01, -7.3237e-01]])


In [70]:
X

tensor([[-0.5985,  0.3188,  0.6822,  0.9907],
        [ 2.5392,  0.8281,  0.1896,  1.0113],
        [-0.6257,  0.6534, -1.5487, -1.2649],
        [-0.9367, -0.8208, -0.0733, -0.2934],
        [-1.1888, -0.4929, -1.3146, -1.2630]])

In [69]:
X[1]

tensor([2.5392, 0.8281, 0.1896, 1.0113])

In [72]:
X[1:]

tensor([[ 2.5392,  0.8281,  0.1896,  1.0113],
        [-0.6257,  0.6534, -1.5487, -1.2649],
        [-0.9367, -0.8208, -0.0733, -0.2934],
        [-1.1888, -0.4929, -1.3146, -1.2630]])

In [73]:
X[:, 1]

tensor([ 0.3188,  0.8281,  0.6534, -0.8208, -0.4929])

In [79]:
X = torch.randn(4, 4)
print(X)

tensor([[-0.2788, -1.2378,  0.6189, -0.7178],
        [-1.1923,  0.7078, -1.1669, -1.5204],
        [ 0.7095, -0.0715,  0.2990,  0.3003],
        [ 1.3313, -0.8713,  1.2750, -0.9517]])


In [76]:
X = X.view(16)
print(X)

tensor([ 0.5503,  1.3769,  0.2271, -0.1897,  0.3775,  0.4012, -1.0758,  0.9342,
         1.0645,  0.3299, -1.1190,  0.0491, -0.4796, -1.9845, -1.4883,  2.2555])


In [82]:
Y = X.view(16)
print(Y)

tensor([-0.2788, -1.2378,  0.6189, -0.7178, -1.1923,  0.7078, -1.1669, -1.5204,
         0.7095, -0.0715,  0.2990,  0.3003,  1.3313, -0.8713,  1.2750, -0.9517])


In [86]:
Z = X.view(-1, 8) # the size -1 is inferred from other dimensions
print(Z)

tensor([[-0.2788, -1.2378,  0.6189, -0.7178, -1.1923,  0.7078, -1.1669, -1.5204],
        [ 0.7095, -0.0715,  0.2990,  0.3003,  1.3313, -0.8713,  1.2750, -0.9517]])


In [87]:
print(Z.size())

torch.Size([2, 8])


In [90]:
X = torch.randn(1)
print(X)
print(X.item())

tensor([-0.8974])
-0.8974248766899109


In [91]:
A = torch.ones(5)
print(A)

tensor([1., 1., 1., 1., 1.])


In [92]:
B = A.numpy()
print(B)

[1. 1. 1. 1. 1.]


In [93]:
A.add_(1)
print(A)
print(B)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [94]:
import numpy as np
A = np.ones(5)
B = torch.from_numpy(A)
np.add(A, 1, out = A)
print(A)
print(B)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [97]:
device = torch.device("cuda") # a CUDA device object
Y = torch.ones_like(X, device = device) # directly create a tensor on GPU
X = X.to(device) # or just use strings ".to("cuda")"
Z = X + Y
print(Z)
print(Z.to("cpu", torch.double))

tensor([0.1026], device='cuda:0')
tensor([0.1026], dtype=torch.float64)


***

In [131]:
X = torch.ones(2,2, requires_grad = True)
print(X)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [139]:
Y = X + 2
print(Y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [142]:
Y.backward?

Signature: Y.backward(gradient=None, retain_graph=None, create_graph=False)
Docstring:
Computes the gradient of current tensor w.r.t. graph leaves.

The graph is differentiated using the chain rule. If the tensor is
non-scalar (i.e. its data has more than one element) and requires
gradient, the function additionally requires specifying ``gradient``.
It should be a tensor of matching type and location, that contains
the gradient of the differentiated function w.r.t. ``self``.

This function accumulates gradients in the leaves - you might need to
zero them before calling it.

Arguments:
    gradient (Tensor or None): Gradient w.r.t. the
        tensor. If it is a tensor, it will be automatically converted
        to a Tensor that does not require grad unless ``create_graph`` is True.
        None values can be specified for scalar Tensors or ones that
        don't require grad. If a None value would be acceptable then
        this argument is optional.
    retain_graph (bool, optional):

In [120]:
Z = Y*3
print(Z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [121]:
Z = Z*Y
print(Z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [122]:
out = Z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [123]:
a = torch.randn(2, 2)
a = ((a*3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [125]:
out.backward()

In [126]:
print(X.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [150]:
X = torch.randn(3, requires_grad = True)

Y = X*2
while Y.data.norm() < 1000:
    Y = Y*2
    
print(Y)

tensor([ 488.2023, -720.7322, -913.4827], grad_fn=<MulBackward0>)


In [151]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
Y.backward(v)

print(X.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


***